import { Weapon } from './types';

export const WEAPONS: Weapon[] = [
  // ── ATTACK ──────────────────────────────────────────────────
  {
    id: 'shell',
    name: 'Shell',
    sub: 'standard shot',
    icon: '💣',
    color: '#f4ecdf',
    rarity: 'common',
    category: 'attack',
    kind: 'single',
    blastRadius: 34,
    damage: 34,
    consumesShot: true,
    shakeAmount: 9,
  },
  {
    id: 'baby_missile',
    name: 'Baby',
    sub: 'small & precise',
    icon: '🚀',
    color: '#a8d8ff',
    rarity: 'common',
    category: 'attack',
    kind: 'single',
    blastRadius: 16,
    damage: 22,
    consumesShot: true,
    shakeAmount: 4,
  },
  {
    id: 'heavy',
    name: 'Heavy',
    sub: 'big crater',
    icon: '🔩',
    color: '#ff9d63',
    rarity: 'common',
    category: 'attack',
    kind: 'single',
    blastRadius: 58,
    damage: 52,
    consumesShot: true,
    shakeAmount: 16,
  },
  {
    id: 'sniper',
    name: 'Sniper',
    sub: 'precision hit',
    icon: '🎯',
    color: '#ff5d5d',
    rarity: 'rare',
    category: 'attack',
    kind: 'single',
    blastRadius: 10,
    damage: 48,
    consumesShot: true,
    shakeAmount: 5,
    speedMult: 1.6,
  },
  {
    id: 'napalm',
    name: 'Napalm',
    sub: 'wide fire zone',
    icon: '🔥',
    color: '#ff4500',
    rarity: 'rare',
    category: 'attack',
    kind: 'napalm',
    blastRadius: 64,
    damage: 28,
    consumesShot: true,
    shakeAmount: 10,
  },
  {
    id: 'cluster',
    name: 'Cluster',
    sub: 'splits ×3',
    icon: '✦',
    color: '#ffce6b',
    rarity: 'common',
    category: 'attack',
    kind: 'cluster',
    blastRadius: 26,
    damage: 22,
    clusterCount: 3,
    clusterSpread: 0.12,
    consumesShot: true,
    shakeAmount: 7,
  },
  {
    id: 'mirv',
    name: 'MIRV',
    sub: 'splits ×6',
    icon: '⚡',
    color: '#c084fc',
    rarity: 'legendary',
    category: 'attack',
    kind: 'mirv',
    blastRadius: 22,
    damage: 18,
    clusterCount: 6,
    clusterSpread: 0.10,
    consumesShot: true,
    shakeAmount: 8,
  },
  {
    id: 'roller',
    name: 'Roller',
    sub: 'rolls to target',
    icon: '⚽',
    color: '#86efac',
    rarity: 'common',
    category: 'attack',
    kind: 'roller',
    blastRadius: 22,
    damage: 30,
    consumesShot: true,
    shakeAmount: 8,
  },
  {
    id: 'homing',
    name: 'Homing',
    sub: 'tracks the foe',
    icon: '🔮',
    color: '#f0abfc',
    rarity: 'rare',
    category: 'attack',
    kind: 'homing',
    blastRadius: 28,
    damage: 30,
    consumesShot: true,
    shakeAmount: 9,
  },
  {
    id: 'tunneler',
    name: 'Tunneler',
    sub: 'digs & erupts',
    icon: '⛏',
    color: '#fb923c',
    rarity: 'rare',
    category: 'attack',
    kind: 'tunneler',
    blastRadius: 40,
    damage: 42,
    consumesShot: true,
    shakeAmount: 14,
  },
  {
    id: 'earthquake',
    name: 'Quake',
    sub: 'rattles terrain',
    icon: '🌊',
    color: '#fbbf24',
    rarity: 'legendary',
    category: 'attack',
    kind: 'earthquake',
    blastRadius: 28,
    damage: 15,
    quakeCount: 8,
    quakeSpread: 180,
    consumesShot: true,
    shakeAmount: 20,
  },
  // ── TERRAIN ─────────────────────────────────────────────────
  {
    id: 'dirt_clod',
    name: 'Dirt Clod',
    sub: 'adds terrain',
    icon: '🪨',
    color: '#a16207',
    rarity: 'common',
    category: 'terrain',
    kind: 'addDirt',
    blastRadius: 28,
    damage: 0,
    dirtRadius: 28,
    consumesShot: true,
    shakeAmount: 3,
  },
  {
    id: 'dirt_wall',
    name: 'Dirt Wall',
    sub: 'builds a wall',
    icon: '🧱',
    color: '#92400e',
    rarity: 'common',
    category: 'terrain',
    kind: 'dirtWall',
    blastRadius: 12,
    damage: 0,
    dirtRadius: 12,
    consumesShot: true,
    shakeAmount: 2,
  },
  // ── UTILITY ─────────────────────────────────────────────────
  {
    id: 'tracer',
    name: 'Tracer',
    sub: 'scout spread — free',
    icon: '👁',
    color: '#00ff66',
    rarity: 'common',
    category: 'utility',
    kind: 'tracer',
    blastRadius: 0,
    damage: 0,
    consumesShot: false,
    shakeAmount: 0,
  },
];

export const RARITY_COLOR: Record<string, string> = {
  common:    'rgba(200,190,180,0.45)',
  rare:      '#3ad9c4',
  legendary: '#ffd060',
};

export const CATEGORY_COLOR: Record<string, string> = {
  attack:  '#ff7a3c',
  terrain: '#a16207',
  utility: '#00ff66',
  defense: '#3ad9c4',
};
