import { Weapon } from './types';

export const WEAPONS: Weapon[] = [
  {
    id: 'shell',
    name: 'Shell',
    sub: 'standard',
    kind: 'single',
    blastRadius: 34,
    damage: 34,
    consumesShot: true,
    shakeAmount: 9,
  },
  {
    id: 'baby_missile',
    name: 'Baby Missile',
    sub: 'small & precise',
    kind: 'single',
    blastRadius: 16,
    damage: 22,
    consumesShot: true,
    shakeAmount: 4,
  },
  {
    id: 'heavy',
    name: 'Heavy Shell',
    sub: 'big crater',
    kind: 'single',
    blastRadius: 58,
    damage: 52,
    consumesShot: true,
    shakeAmount: 16,
  },
  {
    id: 'sniper',
    name: 'Sniper',
    sub: 'tiny, high dmg',
    kind: 'single',
    blastRadius: 10,
    damage: 48,
    consumesShot: true,
    shakeAmount: 5,
  },
  {
    id: 'napalm',
    name: 'Napalm',
    sub: 'wide fire zone',
    kind: 'napalm',
    blastRadius: 64,
    damage: 28,
    consumesShot: true,
    shakeAmount: 10,
  },
  {
    id: 'cluster',
    name: 'Cluster Bomb',
    sub: 'splits ×3',
    kind: 'cluster',
    blastRadius: 26,
    damage: 22,
    clusterCount: 3,
    clusterSpread: 0.12,
    consumesShot: true,
    shakeAmount: 7,
  },
  {
    id: 'mirv',
    name: 'MIRV',
    sub: 'splits ×6',
    kind: 'mirv',
    blastRadius: 22,
    damage: 18,
    clusterCount: 6,
    clusterSpread: 0.10,
    consumesShot: true,
    shakeAmount: 8,
  },
  {
    id: 'roller',
    name: 'Roller',
    sub: 'rolls to target',
    kind: 'roller',
    blastRadius: 22,
    damage: 30,
    consumesShot: true,
    shakeAmount: 8,
  },
  {
    id: 'homing',
    name: 'Homing',
    sub: 'tracks the foe',
    kind: 'homing',
    blastRadius: 28,
    damage: 30,
    consumesShot: true,
    shakeAmount: 9,
  },
  {
    id: 'tunneler',
    name: 'Tunneler',
    sub: 'digs & erupts',
    kind: 'tunneler',
    blastRadius: 40,
    damage: 42,
    consumesShot: true,
    shakeAmount: 14,
  },
  {
    id: 'dirt_clod',
    name: 'Dirt Clod',
    sub: 'adds terrain',
    kind: 'addDirt',
    blastRadius: 28,
    damage: 0,
    dirtRadius: 28,
    consumesShot: true,
    shakeAmount: 3,
  },
  {
    id: 'dirt_wall',
    name: 'Dirt Wall',
    sub: 'builds a wall',
    kind: 'dirtWall',
    blastRadius: 12,
    damage: 0,
    dirtRadius: 12,
    consumesShot: true,
    shakeAmount: 2,
  },
  {
    id: 'earthquake',
    name: 'Earthquake',
    sub: 'rattles terrain',
    kind: 'earthquake',
    blastRadius: 28,
    damage: 15,
    quakeCount: 8,
    quakeSpread: 180,
    consumesShot: true,
    shakeAmount: 20,
  },
  {
    id: 'tracer',
    name: 'Tracer',
    sub: 'scout (free)',
    kind: 'tracer',
    blastRadius: 0,
    damage: 0,
    consumesShot: false,
    shakeAmount: 0,
  },
];
