import { Weapon } from './types';

export const WEAPONS: Weapon[] = [
  {
    id: 'shell',
    name: 'Shell',
    sub: 'standard',
    kind: 'single',
    blastRadius: 34,
    damage: 34,
    consumesShot: true,
    shakeAmount: 9,
  },
  {
    id: 'heavy',
    name: 'Heavy',
    sub: 'big crater',
    kind: 'single',
    blastRadius: 58,
    damage: 52,
    consumesShot: true,
    shakeAmount: 16,
  },
  {
    id: 'cluster',
    name: 'Cluster',
    sub: 'splits ×3',
    kind: 'cluster',
    blastRadius: 26,
    damage: 22,
    clusterCount: 3,
    clusterSpread: 0.12,
    consumesShot: true,
    shakeAmount: 7,
  },
  {
    id: 'roller',
    name: 'Roller',
    sub: 'rolls to target',
    kind: 'roller',
    blastRadius: 20,
    damage: 28,
    consumesShot: true,
    shakeAmount: 8,
  },
  {
    id: 'dirt_clod',
    name: 'Dirt Clod',
    sub: 'adds terrain',
    kind: 'addDirt',
    blastRadius: 28,
    damage: 0,
    dirtRadius: 28,
    consumesShot: true,
    shakeAmount: 3,
  },
  {
    id: 'tracer',
    name: 'Tracer',
    sub: 'scout (free)',
    kind: 'tracer',
    blastRadius: 0,
    damage: 0,
    consumesShot: false,
    shakeAmount: 0,
  },
];
